# Project information
site_name: Kinderphysiotherapie Rita Hensler
site_url: https://kinderphysio-hensler.ch
site_author: Rita Hensler
site_description: >-
  Die Physiotherapie in Winterthur für die Behandlung von Säuglingen, Kindern und Jugendlichen

# Copyright
copyright: >
  Copyright &copy; 2023 Kinderphysiotherapie Rita Hensler<div class="kprh_legal"><a href="/impressum">Impressum</a></div>

# Configuration
theme:
  name: material
  language: de
  palette:
    primary: deep orange
    accent: deep orange
  font: false ## Font not from gstatic
  logo: assets/logo_kinderphysio.svg
  favicon: assets/favicon.png
  features:
    - navigation.footer
extra_css:
  - stylesheets/extra.css
  - fonts/roboto.css
plugins: [] ## Keine Suche
extra:
  generator: false
markdown_extensions:
  - tables
  - attr_list

# Page tree
nav:
  - 'index.md'
  - 'kinderphysiotherapie.md'
  - 'ueber_mich.md'
  - 'kontakt.md'
