# Project information
site_name: Kinderphysiotherapie Rita Hensler
site_url: https://kinderphysio-hensler.ch
site_author: Rita Hensler
site_description: >-
  Die Physiotherapie in Winterthur für die Behandlung von Säuglingen, Kindern und Jugendlichen

# Copyright
copyright: >
  <div class="kprh_legals"><div class="kprh_legal">Copyright &copy; 2023 Kinderphysiotherapie Rita Hensler</div><div class="kprh_legal"><a href="../impressum">Impressum</a></div><div class="kprh_legal"><a href="../datenschutz">Datenschutz</a></div></div>

# Configuration
theme:
  name: material
  language: de
  palette:
    primary: deep orange
    accent: deep orange
  font: false ## Font not from gstatic
  logo: assets/logo_kinderphysio.svg
  favicon: assets/logo_orange.svg
extra_css:
  - stylesheets/extra.css
  - fonts/roboto.css
plugins: [] ## Keine Suche
extra:
  generator: false
markdown_extensions:
  - tables
  - attr_list

# Page tree
nav:
  - Herzlich willkommen: 'index.md'
  - 'kinderphysiotherapie.md'
  - Über mich: 'ueber_mich.md'
  - 'kontakt.md'
