site_name: Kinderphysio Rita Hensler
theme:
  name: material
  language: de
  palette:
    primary: deep orange
  logo: assets/logo_white.png
  features:
    - navigation.footer
copyright: Copyright &copy; 2023 Rita Hensler
extra:
  social:
    - icon: fontawesome/solid/paper-plane
      link: mailto:rita.hensler@physio-hin.ch
      name: E-Mail an Rita Hensler
plugins: []
